theme = "naysayer"

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

# Turn these off to avoid temptation
[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

# Use arrow keys for navigation
[keys.normal]
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
